version: "3.8"
networks:
  unifi:
volumes:
  unifi-mongo-data:
  unifi-config:
services:
  unifi-mongo:
    image: mongo:${MONGO_VERSION:-6.0.15}                   # Required MONGO_VERSION, Default "6.0.15", specify whatever Mongo version tag you need. DO NOT set 'latest' tag
    container_name: unifi-mongo
    environment:
      - MONGO_USER=${MONGO_USER:-unifi}                     # Default "unifi"
      - MONGO_PASS=${MONGO_PASS:?Mongo Password Required}   # Required
      - MONGO_DBNAME=${MONGO_DBNAME:-unifi}                 # Default "unifi"
    volumes:
      - unifi-mongo-data:/data/db
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    networks:
      unifi:
    restart: unless-stopped

  unifi-network-application:
    image: lscr.io/linuxserver/unifi-network-application:latest
    container_name: unifi-network-application
    depends_on: 
      - unifi-mongo
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - MONGO_USER=${MONGO_USER:-unifi}                     # Required, Default "unifi"
      - MONGO_PASS=${MONGO_PASS:?Mongo Password Required}   # Required, Note some special charactor could cause failure to connect to MondoDB
      - MONGO_DBNAME=${MONGO_DBNAME:-unifi}                 # Required, Default "unifi"
      - MONGO_HOST=unifi-mongo                              # Required, must match the mongo container name
      - MONGO_PORT=27017                                    # Required, Must be that same as the mongo container defined port
      - MEM_LIMIT=1024                                    # optional
      - MEM_STARTUP=1024                                  # optional
      # - MONGO_TLS=                                        # optional
      # - MONGO_AUTHSOURCE=                                 # optional
    volumes:
      - unifi-config:/config
    ports:
      - 8443:8443
      - 3478:3478/udp
      - 10001:10001/udp
      - 8080:8080
      - 1900:1900/udp                                       # optional
      # - 8843:8843                                         # optional
      # - 8880:8880                                         # optional
      - 6789:6789                                           # optional
      - 5514:5514/udp                                       # optional
    networks:
      unifi:
    restart: unless-stopped
